### ISSUE TITLE
update pre-commit hook

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/software-templates#35]
### Feature description

We should update the pre-commit version and hooks in .pre-commit-config.yaml for python projects

### Use case

We currently are pointing to v1.4.0, but the latest version is 0.4.6. 
There are also some useful hooks that could be added

### Proposed solution

Update version to 0.4.6 in .pre-commit-config.yaml
consider adding these hooks:
* check-merge-conflict
* detect-aws-credentials

### Additional context

https://github.com/pre-commit/pre-commit-hooks

### Contribution

None

**Comment by jsstevenson** [comment]
It'd be nice to automate this update in the same way that the ruff version update is (theoretically) automatic
