### ISSUE TITLE
Add contributing docs

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/software-templates#4]
I'm working on a draft for biocommons, but I believe we could re-use for our lab + ga4gh projects

**Comment by korikuzma** [comment]
I still think this is needed

**Comment by korikuzma** [comment]
Still want this. Maybe there will be time to work on this during dev fest

**Comment by jsstevenson** [comment]
TODO for this -- add blurb on versioning/release patterns?

**Comment by korikuzma** [comment]
Issue will be addressed here: https://github.com/GenomicMedLab/.github/issues/1 .
