### ISSUE TITLE
Reusable stale workflow requires a version param

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/software-templates#48]
### Describe the bug

Using the stale workflow outside of this repo raises an error: https://github.com/cancervariants/fusor/actions/runs/9907887088/workflow

### Steps to reproduce

n/a

### Expected behavior

n/a

### Current behavior

n/a

### Branch, commit, and/or version

all

### Environment details

n/a

### Contribution

None

**Comment by korikuzma** [comment]
This is because it is missing the reference `@main` at the end. Updated #47 with this.
