### ISSUE TITLE
Make an "update ruff version every X months" github action

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/software-templates#9]
That makes sense to me. Can we create a github bot or something to remind us to update every 3mo-6mo?

_Originally posted by @korikuzma in https://github.com/GenomicMedLab/software-templates/pull/8#pullrequestreview-1863420536_
            
Should be pretty easy: https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation

Other versions to check:

* setuptools?
* Pre-commit
* docs?
* gh actions: checkout and python

This action should auto-open a PR making the relevant changes in this repo.

**Comment by korikuzma** [comment]
I still think this would be nice to have, but still low priority IMO

**Comment by jsstevenson** [comment]
@korikuzma I have actually thought about this a lot (for some reason) and will probably get something basic cooked up in the next week or two

**Comment by jsstevenson** [comment]
I thiiiink this is done in #22 + additional commits. Time will tell!
